### ISSUE TITLE
Redesign Add Text Modal Interface

### ISSUE THREAD

**Issue by ztlee042** [graasp/graasp-builder#1096]
# Todo

- [x] Align fonts with designs? graasp/graasp-ui#772
- [x] Title
  - [x] font
  - [x] color
  - [x] variant graasp/graasp-ui#773
  - [x] text
- [x] Add segmented control to switch btw normal text and html
- [x] Names
  - [x] adjust database accordingly graasp/graasp#891 graasp/graasp-query-client#710
  - [x] add displayName graasp/graasp-sdk#453
  - [x] tips ux & ui
  - [x] supporting text
  - [x] autocomplete
- [x] Flavour -> Type
  - [x] text
  - [x] dropdown list items ui
- [x] write tests

# Preview
![image](https://github.com/graasp/graasp-builder/assets/31677780/3f71d3c3-004b-447c-aceb-7bc4a0db9115)
![image](https://github.com/graasp/graasp-builder/assets/31677780/46e27856-cdab-4c13-8392-37bb27bba3cd)
